In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("suv_data.csv")

In [4]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
x = df.iloc[:,[2,3]]

In [6]:
y = df.iloc[:,-1]

In [9]:
x.head()

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [10]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
st_x = StandardScaler()

In [21]:
x_train = st_x.fit_transform(x_train)

In [22]:
x_test = st_x.transform(x_test)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [48]:
classifier = KNeighborsClassifier(n_neighbors=75)

In [49]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=75)

In [50]:
y_pred = classifier.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
cm = confusion_matrix(y_test,y_pred)

In [53]:
from sklearn.metrics import r2_score

In [54]:
r2 = r2_score(y_test, y_pred)

In [55]:
r2

-1.4999999999999996

In [56]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

In [57]:
accuracy

0.4